apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-ai-config
  namespace: healthcare-ai
  labels:
    app: healthcare-ai-system
data:
  # Environment Configuration
  ENVIRONMENT: "production"
  
  # Network Configuration - NEW: Centralized config system
  NETWORK_HOST: "localhost"
  NETWORK_PROTOCOL: "http"
  EXTERNAL_HOST: "localhost"
  DOMAIN_NAME: ""
  
  # Service URLs - NEW: Dynamic URL generation
  HEALTHCARE_UI_URL: "http://localhost:30080"
  FHIR_MCP_URL: "http://localhost:30084"
  FHIR_PROXY_URL: "http://localhost:30083"
  AGENT_BACKEND_URL: "http://localhost:30082"
  CREWAI_API_URL: "http://localhost:30000"
  AUTOGEN_API_URL: "http://localhost:30001"
  
  # Internal Service URLs (Container DNS)
  FHIR_MCP_INTERNAL_URL: "http://fhir-mcp-service:8004"
  FHIR_PROXY_INTERNAL_URL: "http://fhir-proxy-service:8003"
  AGENT_BACKEND_INTERNAL_URL: "http://agent-backend-service:8002"
  CREWAI_INTERNAL_URL: "http://crewai-service:8000"
  AUTOGEN_INTERNAL_URL: "http://autogen-service:8001"
  
  # FHIR Configuration
  FHIR_BASE_URL: "https://r4.smarthealthit.org"
  
  # Database Configuration
  POSTGRES_DB: "healthcare_ai"
  POSTGRES_USER: "healthcare_user"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Elasticsearch Configuration
  ELASTICSEARCH_HOSTS: "http://elasticsearch-service:9200"
  
  # Environment
  NODE_ENV: "production"
  
  # Legacy Service URLs (for backward compatibility)
  CREWAI_SERVICE_URL: "http://crewai-service:8000"
  AUTOGEN_SERVICE_URL: "http://autogen-service:8001"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: healthcare-ai
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'healthcare-agents'
        static_configs:
          - targets: ['crewai-service:8000', 'autogen-service:8001', 'agent-backend-service:8002']
          
      - job_name: 'healthcare-services'
        static_configs:
          - targets: ['fhir-mcp-service:8004', 'fhir-proxy-service:8003']
          
      - job_name: 'healthcare-ui'
        static_configs:
          - targets: ['healthcare-ui-service:80'] 