apiVersion: v1
kind: Secret
metadata:
  name: healthcare-ai-secrets
  namespace: healthcare-ai
  labels:
    app: healthcare-ai-system
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  # To encode: echo -n "your-secret" | base64
  
  # OpenAI API Key (replace with your encoded key)
  OPENAI_API_KEY: "c2stcHJvai1iYXNlNjQtZW5jb2RlZC1rZXk="
  
  # Database Password
  DATABASE_PASSWORD: "aGVhbHRoY2FyZV9wYXNz"
  POSTGRES_PASSWORD: "aGVhbHRoY2FyZV9wYXNz"
  
  # Redis Password
  REDIS_PASSWORD: "cmVkaXNfcGFzcw=="
  
  # FHIR Client Credentials
  FHIR_CLIENT_ID: "Y2xpZW50X2lk"
  FHIR_CLIENT_SECRET: "Y2xpZW50X3NlY3JldA=="
  
  # Grafana Admin Password
  GRAFANA_PASSWORD: "YWRtaW4="
  
---
# Note: In production, create secrets using kubectl:
# kubectl create secret generic healthcare-ai-secrets \
#   --from-literal=OPENAI_API_KEY="your-actual-api-key" \
#   --from-literal=DATABASE_PASSWORD="your-db-password" \
#   --from-literal=REDIS_PASSWORD="your-redis-password" \
#   --from-literal=FHIR_CLIENT_ID="your-fhir-client-id" \
#   --from-literal=FHIR_CLIENT_SECRET="your-fhir-client-secret" \
#   --from-literal=GRAFANA_PASSWORD="your-grafana-password" \
#   --namespace=healthcare-ai 